<a href="https://colab.research.google.com/github/Potdooshami/planar-domain-wall-network/blob/main/smithForm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install hsnf

In [ ]:
import numpy as np
from hsnf import column_style_hermite_normal_form, row_style_hermite_normal_form, smith_normal_form

# Integer matrix to be decomposed
M = np.array(
    [
        [4,0,0,   0,0,0,  0],
        [0,4,0,   0,0,0,  0],
        [0,0,4,   0,0,0,  0],
        [0,0,0,   4,0,0,  0],
        [0,0,0,   0,4,0,  0],
        [0,0,0,   0,0,4,  0],
        [0,0,0,   0,0,0,  4],

        [1,1,1,   0,0,0,  1],

        [1,0,0,   0,1,-1,  -1],
        [0,1,0,   -1,0,1,  -1],
        [0,0,1,   1,-1,0,  -1],

        [0,1,-1,   0,-1,-1,  0],
        [-1,0,1,   -1,0,-1,  0],
        [1,-1,0,   -1,-1,0,  0],
    ]
)
#M = np.array([[1,-1,-1,1],[0,1,-1,0]])
M = np.array([[2,3,6]]`)
# Smith normal form
D, L, R = smith_normal_form(M)

In [ ]:
print(D)
print(L)
print(R)

[[1 0 0]]
[[1]]
[[-1  3 -3]
 [ 1 -2  0]
 [ 0  0  1]]


In [ ]:
print(


)