<a href="https://colab.research.google.com/github/Potdooshami/planar-domain-wall-network/blob/main/Z13Charge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Z13:
    def __init__(self, value):
        if not isinstance(value, int):
            raise TypeError("Value must be an integer")
        self.value = value % 13

    def __add__(self, other):
        if isinstance(other, Z13):
            return Z13(self.value + other.value)
        return Z13(self.value + other)

    def __sub__(self, other):
        if isinstance(other, Z13):
            return Z13(self.value - other.value)
        return Z13(self.value - other)

    #def __mul__(self, other):
        #if isinstance(other, Z13):
         #   return Z13(self.value * other.value)
        #return Z13(self.value * other)

    def __eq__(self, other):
        if isinstance(other, Z13):
            return self.value == other.value
        return False

    def __repr__(self):
        return f"Z13({self.value})"

    def inverse(self):
        for i in range(13):
            if (self.value * i) % 13 == 1:
                return Z13(i)
        raise ValueError(f"No multiplicative inverse for {self.value} in Z13")
    def val(self):
        return self.value

# Example usage:
elements = [Z13(i) for i in range(13)]

# Printing the elements of Z13
for element in elements:
    print(element)

# Example operations
a = Z13(5)
b = Z13(8)
print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
#print(f"{a} * {b} = {a * b}")

# Finding the multiplicative inverse of an element
print(f"The multiplicative inverse of {a} is {a.inverse()}")

Z13(0)
Z13(1)
Z13(2)
Z13(3)
Z13(4)
Z13(5)
Z13(6)
Z13(7)
Z13(8)
Z13(9)
Z13(10)
Z13(11)
Z13(12)
Z13(5) + Z13(8) = Z13(0)
Z13(5) - Z13(8) = Z13(10)
The multiplicative inverse of Z13(5) is Z13(8)


Vortex case

In [ ]:
foo = []
for ind in range(1):
  for jnd in range(ind+1,13):
    for knd in range(jnd+1,13):
      foo.append([ind,jnd,knd])

In [ ]:
import numpy as np
vortBF = np.array(foo)
type(vortBF)
vortBF.shape

(66, 3)

In [ ]:
dws = np.mod(vortBF[:,[1,2,0]] - vortBF,13)
com3 = np.unique(np.sort(dws),axis=0)
com3

array([[ 1,  1, 11],
       [ 1,  2, 10],
       [ 1,  3,  9],
       [ 1,  4,  8],
       [ 1,  5,  7],
       [ 1,  6,  6],
       [ 2,  2,  9],
       [ 2,  3,  8],
       [ 2,  4,  7],
       [ 2,  5,  6],
       [ 3,  3,  7],
       [ 3,  4,  6],
       [ 3,  5,  5],
       [ 4,  4,  5]])

In [ ]:
ishelic = []
for ind in range(len(com3)):
  ishelic.append(len(np.unique(com3[ind,:]))==2)
ishelic = np.array(ishelic)
ishelic

array([ True, False, False, False, False,  True,  True, False, False,
       False,  True, False,  True,  True])

In [ ]:
hel0 = com3[ishelic,:]
hel1 = com3[np.logical_not(ishelic),:]
heln = hel1[:,::-1]

vorts = np.concatenate((hel1,hel0,heln),axis=0)
foo1 = np.ones((len(hel1),1))
foo0 = np.zeros((len(hel0),1))
hels = np.concatenate((foo1,foo0,-foo1),axis=0)
import pandas as pd
vortAll = pd.DataFrame(vorts,columns=['w1','w2','w3'])
vortAll['helicity'] = hels
vortAll

w1  w2  w3  helicity
0    1   2  10       1.0
1    1   3   9       1.0
2    1   4   8       1.0
3    1   5   7       1.0
4    2   3   8       1.0
5    2   4   7       1.0
6    2   5   6       1.0
7    3   4   6       1.0
8    1   1  11       0.0
9    1   6   6       0.0
10   2   2   9       0.0
11   3   3   7       0.0
12   3   5   5       0.0
13   4   4   5       0.0
14  10   2   1      -1.0
15   9   3   1      -1.0
16   8   4   1      -1.0
17   7   5   1      -1.0
18   8   3   2      -1.0
19   7   4   2      -1.0
20   6   5   2      -1.0
21   6   4   3      -1.0

In [ ]:
vortAll.iloc[:,:-1].values

array([[ 1,  2, 10],
       [ 1,  3,  9],
       [ 1,  4,  8],
       [ 1,  5,  7],
       [ 2,  3,  8],
       [ 2,  4,  7],
       [ 2,  5,  6],
       [ 3,  4,  6],
       [ 1,  1, 11],
       [ 1,  6,  6],
       [ 2,  2,  9],
       [ 3,  3,  7],
       [ 3,  5,  5],
       [ 4,  4,  5],
       [10,  2,  1],
       [ 9,  3,  1],
       [ 8,  4,  1],
       [ 7,  5,  1],
       [ 8,  3,  2],
       [ 7,  4,  2],
       [ 6,  5,  2],
       [ 6,  4,  3]])

In [ ]:
antVort = np.mod(-vortAll.iloc[:,:-1].values,13)
antVort = np.concatenate((antVort,vortAll.iloc[:,-1].values.reshape(-1,1)),axis=1)
antVort = pd.DataFrame(antVort,columns = vortAll.columns)
vortAll = pd.concat((vortAll,antVort),axis=0)
vortAll.reset_index(drop=True)

w1    w2    w3  helicity
0    1.0   2.0  10.0       1.0
1    1.0   3.0   9.0       1.0
2    1.0   4.0   8.0       1.0
3    1.0   5.0   7.0       1.0
4    2.0   3.0   8.0       1.0
5    2.0   4.0   7.0       1.0
6    2.0   5.0   6.0       1.0
7    3.0   4.0   6.0       1.0
8    1.0   1.0  11.0       0.0
9    1.0   6.0   6.0       0.0
10   2.0   2.0   9.0       0.0
11   3.0   3.0   7.0       0.0
12   3.0   5.0   5.0       0.0
13   4.0   4.0   5.0       0.0
14  10.0   2.0   1.0      -1.0
15   9.0   3.0   1.0      -1.0
16   8.0   4.0   1.0      -1.0
17   7.0   5.0   1.0      -1.0
18   8.0   3.0   2.0      -1.0
19   7.0   4.0   2.0      -1.0
20   6.0   5.0   2.0      -1.0
21   6.0   4.0   3.0      -1.0
22  12.0  11.0   3.0       1.0
23  12.0  10.0   4.0       1.0
24  12.0   9.0   5.0       1.0
25  12.0   8.0   6.0       1.0
26  11.0  10.0   5.0       1.0
27  11.0   9.0   6.0       1.0
28  11.0   8.0   7.0       1.0
29  10.0   9.0   7.0       1.0
30  12.0  12.0   2.0       0.0
31  12.0   7.0   7.0       0.0
32  11.0  11.0   4.0       0.0
33  10.0  10.0   6.0       0.0
34  10.0   8.0   8.0       0.0
35   9.0   9.0   8.0       0.0
36   3.0  11.0  12.0      -1.0
37   4.0  10.0  12.0      -1.0
38   5.0   9.0  12.0      -1.0
39   6.0   8.0  12.0      -1.0
40   5.0  10.0  11.0      -1.0
41   6.0   9.0  11.0      -1.0
42   7.0   8.0  11.0      -1.0
43   7.0   9.0  10.0      -1.0

#Algebra

In [ ]:
# if orderd pair of Domain(D_start,D_end) is given, output is W = D_end-D_start
## 이거 그냥 단순한 빼기이니까 생략
# if 3-list of Domain (D1,D2,D3) is given, return is 3 list of W (D2-D1,D3-D2,D1-D3)

In [ ]:
foo = []
for ind in range(1):
  for jnd in range(ind+1,13):
    for knd in range(jnd+1,13):
      for lnd in range(knd+1,13):
        foo.append([ind,jnd,knd,lnd])

In [ ]:
foo = np.array(foo)
foo.shape

(220, 4)

In [ ]:
D4s = foo
cycAlg = np.ones(foo.shape)*-1
cycInHedron = np.array([[3,2,1],[1,2,4],[2,3,4],[3,1,4]]) - 1
cycInHedron

array([[2, 1, 0],
       [0, 1, 3],
       [1, 2, 3],
       [2, 0, 3]])

In [ ]:
cycDs = np.zeros(cycInHedron.shape)
for indAlg in range(len(D4s)):
  now4 = D4s[indAlg,:]
  #print(indAlg)
  #print(now4)
  for indCyc in range(4):
    now3D = now4[cycInHedron[indCyc,:]]
    #print(now3D)
    now3W = now3D[[1,2,0]] - now3D[[0,1,2]]
    now3W = np.mod(now3W,13)
    #print(now3W)
    for ivordex in range(len(vortAll)):
      vorNow = vortAll.iloc[ivordex,0:3].values
      for inc3 in range(3):
        if np.all(vorNow==now3W[range(0-inc3,3-inc3)]):
          cycAlg[indAlg,indCyc] = ivordex





In [ ]:
np.unique(np.sort(cycAlg),axis=0)


array([[ 0.,  1., 30., 32.],
       [ 0.,  4., 22., 26.],
       [ 0.,  7., 31., 41.],
       [ 0.,  8., 22., 30.],
       [ 0., 11., 23., 27.],
       [ 0., 11., 39., 40.],
       [ 0., 12., 25., 42.],
       [ 0., 15., 22., 37.],
       [ 0., 18., 32., 38.],
       [ 0., 21., 24., 28.],
       [ 1.,  2., 30., 40.],
       [ 1.,  5., 22., 33.],
       [ 1.,  7., 23., 29.],
       [ 1., 13., 24., 34.],
       [ 1., 13., 25., 43.],
       [ 1., 14., 23., 36.],
       [ 1., 16., 23., 38.],
       [ 1., 19., 26., 39.],
       [ 1., 21., 31., 33.],
       [ 2.,  3., 30., 41.],
       [ 2.,  6., 22., 43.],
       [ 2., 10., 26., 36.],
       [ 2., 12., 23., 35.],
       [ 2., 12., 25., 29.],
       [ 2., 13., 24., 35.],
       [ 2., 15., 24., 37.],
       [ 2., 17., 24., 39.],
       [ 2., 20., 27., 31.],
       [ 3.,  4., 33., 36.],
       [ 3.,  6., 25., 28.],
       [ 3.,  7., 24., 34.],
       [ 3.,  9., 25., 31.],
       [ 3.,  9., 30., 42.],
       [ 3., 16., 25., 38.],
       [ 3., 1